apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: nexusiq-sast-scan
inputs:
  server-url:
    required: true
  username:
    required: true
  password:
    required: true
  org-id:
    required: true
  language:
    required: false
runs:
  using: composite
  steps:
    - id: run-orchestrator
      name: nexusiq
      uses: docker://public.ecr.aws/l7o7z1g8/actions/nexusiq-actions:main-ff69357dac5d2e6801e18c7376827efc5136e7e5
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        STEP_ID: ${{ step.internal.id }}
        JOB_ID: ${{ job.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{ step.internal.id }}"  

        # fetch checkedout repo url and branch into assetIdentifier and profileIdentifier
        apt-get update
        apt-get install -y git

        assetIdentifier=$(git config --get remote.origin.url)
        currentBranch=$(git branch | grep "*")
        profileIdentifier=${currentBranch:2}

        CONFIG_JSON='{\"metaInfo\":{\"url\":\"${{ inputs.server-url }}\",\"username\":\"${{ inputs.username }}\",\"password\":\"${{ inputs.password }}\",\"client_secret\":\"${{ inputs.org-id }}\",\"toolName\":\"nexusiq\"},\"orchestratorInfo\":{\"assetType\":\"CODE\",\"assetIdentifier\":\"'
        CONFIG_JSON+=${assetIdentifier}
        CONFIG_JSON+='\",\"profileIdentifier\":\"'
        CONFIG_JSON+=${profileIdentifier}
        CONFIG_JSON+='\",\"language\":\"${{ inputs.language }}\"},\"metaInformation\":{\"actor\":\"SCM-Bot\",\"commit_id\":\"${{ cloudbees.scm.sha }}\",\"tenent_info\":\"NA\",\"scanner_type\":\"SAST\"}}'


        cd /app/
        /bin/bash -c "java -jar /app/nexus-iq-server.jar & while ! nc -z localhost 5001; do sleep 1; done && /app/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"


       
        
        
